[project]
name = "audio-noise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "audioop-lts>=0.2.1",
    "numpy>=2.3.1",
    "pydub>=0.25.1",
    "scipy>=1.16.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
